title: MIRS Perfumes
description: MIRS je EDP parfem za žene koji spaja sofisticiranost i neukrotivu prirodu.
baseurl: "/  # Mora početi s kosom crtom, naziv repozitorija
url: "https://mirsperfumes.eu"
permalink: /blog/:title/
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
