title: MIRS Perfumes
description: MIRS je EDP parfem za žene koji spaja sofisticiranost i neukrotivu prirodu.
baseurl: "/"  # Mora početi s kosom crtom, naziv repozitorija
url: "https://mirsperfumes.eu"
permalink: /blog/:title/
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  
defaults:
  - scope:
      path: "" # an empty string here means all files of a type
      type: "posts"
    values:
      description: ""
      author: ""
      image: ""
      layout: post
      